<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIRZOBPA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIRZOBPA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIRZOBPA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIRZOBPA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIRZOBPA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IRZOBPA',
    'container.build_id' => '0edd85cf',
    'container.build_time' => 1681085400,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIRZOBPA');
